### ISSUE TITLE
Mouse cursor hidden by application

### ISSUE THREAD

**Issue by nathanesau** [3snowp7im/urn#5] opened 2015-05-31 04:39 UTC
I noticed that the application region hides the mouse cursor which makes it a little difficult to get to the File Menu. Not sure to this could be fixed (or whether it is easy to fix with GTK?)

**Comment by codl** [comment] 2015-05-31 09:46
Maybe only hide the cursor when it is over the main area, not the menubar? Also it would be nice if Alt+F opened the File menu.

Note that you can disable hiding the cursor entirely by running `gsettings set wildmouse.urn hide-cursor false`.

**Comment by johnoliverdriscoll** [comment] 2015-06-13 02:57
I plan on implementing some menu hotkeys soon, hopefully I can spend some time on urn this weekend.

Closing issue, as cursor hiding is the intended behavior. As codl pointed out, you can modify your settings to disable this feature.

**Closed** 2015-06-19 06:53 UTC
